service: sls-wormhole

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_REGION, 'ca-central-1'}
  stage: ${env:STAGE, 'dev'}

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline


package:
  patterns: "*"


functions:
  auth:
    description: POST token for further calls
    handler: src/main/lambda-functions/auth/index.getUserTokenHandler
    timeout: 30
    memorySize: 2048
    events:
      - http:
          path: auth
          method: POST
  leaderboard-position-user:
    description: Get 15 users above, and current position
    handler: src/main/lambda-functions/userPosition/index.getUserPositionHandler
    timeout: 30
    memorySize: 2048
    events:
      - http:
          path: leaderboard-position-user
          method: GET
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: WormholeApiGatewayAuthorizer
  top-100-users:
    description: Get top 100 users
    handler: src/main/lambda-functions/top100Users/index.getTop100UsersHandler
    timeout: 30
    memorySize: 2048
    events:
      - http:
          path: top-100-users
          method: GET
  upsert-user:
    description: Called to upsert user
    handler: src/main/lambda-functions/upsertUser/index.upsertUserHandler
    timeout: 30
    memorySize: 2048
    events:
      - http:
          path: upsert-user
          method: POST
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: WormholeApiGatewayAuthorizer

resources:
  Resources:
    WormholeCognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: Wormhole
    WormholeCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: WormholeWebApp
        GenerateSecret: false
        UserPoolId:
          Ref: "WormholeCognitoUserPool"
    WormholeDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: BestTime
            AttributeType: S
          - AttributeName: SteamId
            AttributeType: S
        KeySchema:
          - AttributeName: SteamId
            KeyType: HASH 
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1      
        GlobalSecondaryIndexes:
        - IndexName: BestTime_Index
          Projection:
            ProjectionType: 'ALL'
          KeySchema:
            - AttributeName: SteamId
              KeyType: HASH
            - AttributeName: BestTime
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
    WormholeLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: WormholeLambda
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DynamoDBWriteAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: 
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                  Resource:
                    'Fn::GetAtt': [ WormholeDynamoDBTable, Arn ]
    WormholeApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: Wormhole
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - Fn::GetAtt: [ WormholeCognitoUserPool, Arn ]
        IdentitySource: method.request.header.Authorization
  Outputs:
    WormholeCognitoUserPoolId:
      Description: "Wormhole Cognito User Pool ID"
      Value:
        Ref: "WormholeCognitoUserPool"
    WormholeCognitoUserPoolClientId:
      Description: "Wormhole Cognito User Pool Client ID"
      Value:
        Ref: "WormholeCognitoUserPoolClient"
    WormholeDynamoDbARN:
      Description: "Wormhole DynamoDB ARN"
      Value:
        "Fn::GetAtt": [ WormholeDynamoDBTable, Arn ]
